<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Возврат / обмен товара</title>

	<meta name="format-detection" content="telephone=no">
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<meta name="description" content="Как стать поставщиком">
	<meta name="keywords" content="О интернет магазине Сатерно">

	<link rel="stylesheet" href="App/templates/files/bootstrap.min.css">
	<link rel="stylesheet" href="App/templates/files/font-awesome.min.css">
	<link rel="stylesheet" href="App/templates/files/lib.css">
	<link rel="stylesheet" href="App/templates/files/ie9-and-up.css">
	<link rel="stylesheet" href="App/templates/files/style.css">
	<link rel="stylesheet" href="App/templates/files/style(1).css">
	<link rel="stylesheet" href="App/templates/files/so_sociallogin.css">
	<link rel="stylesheet" href="App/templates/files/so_searchpro.css">
	<link rel="stylesheet" href="App/templates/files/so_megamenu.css">
	<link rel="stylesheet" href="App/templates/files/wide-grid.css">
	<link rel="stylesheet" href="App/templates/files/custom.css">
	<link rel="stylesheet" href="App/templates/files/owl.carousel.css">
	<link rel="stylesheet" href="App/templates/files/orange.css">
	<link rel="stylesheet" href="App/templates/files/header1.css">
	<link rel="stylesheet" href="App/templates/files/footer1.css">
	<link rel="stylesheet" href="App/templates/files/responsive.css">
	<link rel="stylesheet" href="App/templates/files/css/popUp.css">
	<link rel="stylesheet" href="App/templates/files/css/buyCart.css">
	<link rel="stylesheet" href="App/templates/files/css/inputsAndTextareasDefault.css">
	<script async="" src="App/templates/files/js/tag.js"></script><script src="App/templates/files/js/jquery-2.1.1.min.js"></script>
	<script src="App/templates/files/js/bootstrap.min.js"></script>
	<script src="App/templates/files/js/libs.js"></script>
	<script src="App/templates/files/js/so.system.js"></script>
	<script src="App/templates/files/js/so.custom.js"></script>
	<script src="App/templates/files/js/common.js"></script>
	<script src="App/templates/files/js/jquery.unveil.js"></script>
	<script src="App/templates/files/js/owl.carousel.js"></script>
	<script src="App/templates/files/js/script.js"></script>
	<script src="App/templates/files/js/so_megamenu.js"></script>

	<link href="App/templates/index_files/saternologomini.jpg" rel="icon">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,500,300,700,900' rel='stylesheet' type='text/css'> 	
	<link rel="stylesheet" href="App/templates/files/css/styleForAll.css">
</head>

<body class="information-information-4 ltr res layout-1   loaded">

<?php require(__DIR__ . "/files/html/modal_sign_to_account.html");?>

<div id="wrapper" class="wrapper-full banners-effect-7">   
	
		<div class="loader-content">
		<div id="loader">
						<div class="cssload-thecube"><div class="cssload-cube cssload-c1"></div><div class="cssload-cube cssload-c2"></div><div class="cssload-cube cssload-c4"></div><div class="cssload-cube cssload-c3"></div></div>
				</div>
	</div>

<?php require(__DIR__ . "/files/html/header.html");?>
	
	<div id="socialLogin"></div>

	
<div class="container">
   <!-- BREADCRUMB -->
	<ul class="breadcrumb">
				<li><a href="/home"><i class="fa fa-home"></i></a></li>
				<li><a href="/terms">Возврат / обмен товара</a></li>
			</ul>
</div>

<div class="container">
  <div class="">
                      <div id="content" class="">
		
        <div class="container">
			
<div class="modalBlock toggleModal0" data-toggle="true" role="dialog" aria-labelledby="modalTitle" aria-describedby="modalDescription" data-state="close" style="overflow: auto;">
  <div class="modal__block">
	<div class="modalHeader">
		<div class="title">Выбор модели</div>
		<button class="modal__close toggleModal0" data-toggle="true">
			<svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg">
				<path d="M8.414 7l4.95-4.95L11.948.638 7 5.587 2.05.636.638 2.05 5.587 7l-4.95 4.95 1.414 1.413L7 8.413l4.95 4.95 1.413-1.414L8.413 7z" fill-rule="evenodd"></path>
			</svg>
		</button>
	</div>			
	<div class="modalBody">
		<div>
		    <p>Добавление товара «<span class="product-title"></span>» в корзину</p>
		    <div class="price" style="">
		        <p class="price-title" style="margin: 0; line-height: 0.8; font-size: 13px; font-weight: 400; color: #3b3b3b">Цена</p>
		        <p class="price-value" style=" font-size: 21px; font-weight: 900; "></p>
		    </div>
		    <div class="atributes">
		        
		    </div>
		    <p class="pButtonBuy" style="margin: 0; padding: 10px;">
    		    <span class="svg buttonBuy">
        			<svg height="24" width="24" style="fill: #000;cursor: pointer;">
        			    <svg viewBox="0 0 24 24" id="icon-basket">
                        	<g>
                        		<path fill-rule="evenodd" clip-rule="evenodd" d="M1 2C0.447715 2 0 2.44772 0 3C0 3.55228 0.447715 4 1 4H2.68121C3.08124 4 3.44277 4.2384 3.60035 4.60608L8.44161 15.9023C9.00044 17.2063 10.3963 17.9405 11.7874 17.6623L19.058 16.2082C20.1137 15.9971 20.9753 15.2365 21.3157 14.2151L23.0712 8.94868C23.7187 7.00609 22.2728 5 20.2251 5H5.94511L5.43864 3.81824C4.96591 2.71519 3.88129 2 2.68121 2H1ZM10.2799 15.1145L6.80225 7H20.2251C20.9077 7 21.3897 7.6687 21.1738 8.31623L19.4183 13.5827C19.3049 13.9231 19.0177 14.1767 18.6658 14.247L11.3952 15.7012C10.9315 15.7939 10.4662 15.5492 10.2799 15.1145Z"></path>
                        		<path d="M11 22C11 23.1046 10.1046 24 9 24C7.89543 24 7 23.1046 7 22C7 20.8954 7.89543 20 9 20C10.1046 20 11 20.8954 11 22Z"></path>
                        		<path d="M21 22C21 23.1046 20.1046 24 19 24C17.8954 24 17 23.1046 17 22C17 20.8954 17.8954 20 19 20C20.1046 20 21 20.8954 21 22Z"></path>
                        	</g>
                        </svg>
        			</svg>
    			</span>
			</p>
		</div>
	</div>
	
  </div>
</div>

<?php require(__DIR__ . "/files/html/buy-cart-module.html"); ?>

<?php require(__DIR__ . "/files/html/right_menu.html"); ?>

<div id="cover"></div>
<div id="cover2"></div>
<div id="cover3"></div>

<script src="App/templates/files/js/popUp.js"></script>
<script src="App/templates/files/js/buyCartModule.js"></script>
			
			<h1 style="margin-top: 20px; margin-bottom: 10px; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(68, 68, 68);">Возврат / обмен товара<br></h1>
<h3 style="margin-top: 20px; margin-bottom: 10px; font-family: &quot;Open Sans&quot;, sans-serif; color: rgb(68, 68, 68);">Данные правила относятся к покупателям, которые приобретают товар исключительно для нужд, не связанных с осуществлением предпринимательской деятельности.<br></h3>
<h2 style="font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; line-height: inherit; color: rgb(36, 36, 36); margin: 20px 0px 1em; font-size: 1.25em; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; vertical-align: baseline; text-transform: uppercase; text-align: center; letter-spacing: 0.5px;">1. ОБМЕН И ВОЗВРАТ НЕПРОДОВОЛЬСТВЕННОГО ТОВАРА НАДЛЕЖАЩЕГО КАЧЕСТВА</h2>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Необходимые условия (должны быть соблюдены все):<br></span>1. Товар не&nbsp;был в&nbsp;употреблении.<br>2. Сохранён товарный вид (товар не&nbsp;имеет следов использования). Не&nbsp;повреждена упаковка товара (вскрыта, но&nbsp;не&nbsp;разорвана). Если вы&nbsp;возвращаете товар в&nbsp;интернет-магазин через курьерскую почту, допускается, чтобы упаковка была помята.<br>3. Сохранены потребительские свойства. Мы&nbsp;вправе провести проверку на&nbsp;сохранность потребительских свойств возвращаемого товара.<br>4. Не прошёл остаточный срок годности.<br>5. Сохранены ярлыки и&nbsp;пломбы.<br>6. Предоставление документа, подтверждающего факт и&nbsp;условия покупки указанного товара у&nbsp;нас (товарный или кассовый чек либо иные подтверждающие оплату указанного товара документы) с&nbsp;гарантийными сроками или сроками годности (службы).<br>Если данный документ у&nbsp;Вас не&nbsp;сохранился, возврат товара возможен, если есть доказательства приобретения товара у&nbsp;нас (иные документы, штампы на&nbsp;упаковке, электронная переписка).<br>7. Товар не&nbsp;был разработан специально под конкретного заказчика.<br>8. Товар не&nbsp;входил в&nbsp;«<a href="http://www.consultant.ru/document/cons_doc_LAW_17579/c8b966271331ed0f59b793d7144df9b88335c640/" style="color: rgb(43, 43, 43); margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Перечень непродовольственных товаров надлежащего качества, не&nbsp;подлежащих возврату или обмену на&nbsp;аналогичный товар других размеров, формы, габарита, фасона, расцветки или комплектации</a>» (утв. Постановлением Правительства РФ&nbsp;от&nbsp;19.01.1998 г. №&nbsp;55).<br>В&nbsp;этот перечень в&nbsp;том числе входят:</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Товары из&nbsp;нетканых материалов типа тканей, кабельная продукция (провода, шнуры, кабели); строительные и&nbsp;отделочные материалы (линолеум, плёнка, ковровые покрытия и т. д.) и&nbsp;другие товары, отпускаемые на&nbsp;метраж.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Швейные и&nbsp;трикотажные изделия.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Товары бытовой химии, пестициды и&nbsp;агрохимикаты.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Мебель бытовая (мебельные гарнитуры и&nbsp;комплекты).</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Электронные игрушки.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Гражданское оружие, основные части гражданского и&nbsp;служебного огнестрельного оружия, патроны к&nbsp;нему.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Электробытовые машины и&nbsp;приборы.</p>
<h2 style="font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; line-height: inherit; color: rgb(36, 36, 36); margin: 20px 0px 1em; font-size: 1.25em; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; vertical-align: baseline; text-transform: uppercase; text-align: center; letter-spacing: 0.5px;">1.1. ВОЗВРАТ НЕПРОДОВОЛЬСТВЕННОГО ТОВАРА НАДЛЕЖАЩЕГО КАЧЕСТВА</h2>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; color: rgb(0, 0, 0); font-family: &quot;Century Gothic&quot;; font-size: 12px; letter-spacing: normal; text-align: justify;"><font size="4">Гарантия возврата не продовольственного товара&nbsp;<u>надлежащего</u>&nbsp;качества</font></span><font size="4" style="color: rgb(0, 0, 0); font-family: &quot;Century Gothic&quot;; letter-spacing: normal; text-align: justify;">&nbsp;в интернет магазине Сатерно, согласно закона "О защите прав потребителей" от 07 февраля 1992 года № 2300-1 составляет:<br>&nbsp;<br><u>- в момент, пока товар не получен</u>: в любое время.<br>&nbsp;<br><u>- после получения товара</u>, в течении 7 дней. Т.е. после получения товара, покупатель интернет магазина Сатерно имеет право вернуть товар, если он не подошел по каким либо параметрам или покупатель просто передумал.<br>&nbsp;<br></font><span style="color: rgb(0, 0, 0); font-family: &quot;Century Gothic&quot;; font-size: 12px; letter-spacing: normal; text-align: justify;"></span><span style="font-weight: 700; color: rgb(0, 0, 0); font-family: &quot;Century Gothic&quot;; font-size: 12px; letter-spacing: normal; text-align: justify;"><font size="4">Гарантия возврата не продовольственного товара&nbsp;<u>ненадлежащего</u>&nbsp;качества&nbsp;</font></span><font size="4" style="color: rgb(0, 0, 0); font-family: &quot;Century Gothic&quot;; letter-spacing: normal; text-align: justify;">в интернет магазине Сатерно, согласно закона "О защите прав потребителей" от 07 февраля 1992 года № 2300-1 составляет:<br>&nbsp;<br><u>- в момент, пока товар не получен</u>: в любое время.<br>&nbsp;<br><u>- после получения товара</u>, в течении гарантийного срока установленного заводом изготовителем, но минимум 6 месяцев, если гарантийный срок не установлен.&nbsp;</font><br><br></p>
<h2 style="font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; line-height: inherit; color: rgb(36, 36, 36); margin: 20px 0px 1em; font-size: 1.25em; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; vertical-align: baseline; text-transform: uppercase; text-align: center; letter-spacing: 0.5px;">1.2. ОБМЕН НЕПРОДОВОЛЬСТВЕННОГО ТОВАРА НАДЛЕЖАЩЕГО КАЧЕСТВА</h2>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Вы&nbsp;можете обменять купленный товар на&nbsp;аналогичный – другого размера, формы, габарита, фасона, расцветки или комплектации – и, в&nbsp;случае разницы в&nbsp;цене, мы&nbsp;сделаем необходимый перерасчёт. Обмен происходит&nbsp;<a href="https://y-skazki.ru/contacts/" style="color: rgb(43, 43, 43); margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">в&nbsp;месте покупки</a>&nbsp;и&nbsp;иных местах, оговоренных нами.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Срок</span><br>14 дней с&nbsp;момента передачи Вам товара (если более длительный срок не&nbsp;объявлен нами).<br><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если необходимый для обмена товар отсутствует в&nbsp;продаже в&nbsp;день Вашего обращения</span>, Вы&nbsp;можете вернуть приобретённый товар нам и&nbsp;получить оплаченную за&nbsp;него денежную сумму. По&nbsp;соглашению мы&nbsp;можем обменять товар, когда аналогичный товар поступит в&nbsp;продажу, сообщив Вам о&nbsp;его поступлении.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">2. Обмен и возврат товара ненадлежащего качества</span></p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Товар ненадлежащего качества – это неисправный товар, который не может обеспечить исполнение своих функциональных качеств.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Существенное нарушение требований к его качеству – это неустранимые недостатки, недостатки, которые не могут быть устранены без несоразмерных расходов или затрат времени, либо выявляются неоднократно, либо проявляются вновь после их устранения, и другие подобные недостатки.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Необходимые условия:<br></span>1. Требования покупателя в&nbsp;письменной форме, связанные с&nbsp;недостатками товара.<br>2. Технический паспорт или иной заменяющий его документ.<br>3. Гарантийный талон (если на товар установлен гарантийный срок).<br>4. Документы, подтверждающие недостатки товара и&nbsp;убытки, причиненные покупателю в&nbsp;связи с&nbsp;ненадлежащим качеством товара.<br>5. Кассовый или товарный чек либо иной документ, удостоверяющий факт и условия покупки товара в нашем магазине. Если Вы не сохранили эти документы, Вы можете доказать факт и условия покупки другими способами.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Мы не отвечаем за недостатки товара, если они возникли после передачи товара Вам вследствие нарушения Вами правил использования, хранения или транспортировки товара, действий третьих лиц или непреодолимой силы.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">В момент доставки товара проверяйте внешний вид и комплектность товара, а также комплектность всего заказа. При доставке товара Вы должны расписаться в квитанции о доставке в графе «Заказ принял, комплектность полная, услуги по доставке оказаны, претензий к количеству и внешнему виду товара не имею. С условиями возврата товара ознакомлен». После получения заказа претензии к внешним дефектам товара, его количеству, комплектности и товарному виду не принимаются.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">В связи с особенностями дистанционного способа продажи, замена товара, купленного через интернет-магазин, может быть выполнена только посредством возврата товара ненадлежащего качества и оформления нового заказа на аналогичный товар.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Если купленный у&nbsp;нас товар оказался ненадлежащего качества и&nbsp;его недостатки не&nbsp;были оговорены нами, мы&nbsp;по&nbsp;вашему выбору:</p>
<table border="1" cellspacing="0" cellpadding="10" style="background: rgb(242, 219, 219); margin: 0px; padding: 0px; border: 1pt solid windowtext; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">
<tbody style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Заменим товар:</span><br>- на товар этой же марки (этих же модели и (или) артикула);<br>- на такой же товар другой марки (модели, артикула) с соответствующим перерасчётом покупной цены.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Уменьшим покупную цену</span><br>соразмерно недостаткам</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Безвозмездно устраним недостаток</span><br>(или возместим расходы на такое устранение)</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Примем товар обратно</span></p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В течение 7 дней со дня требования, а при необходимости дополнительной проверки качества такого товара - в течение 20 дней со дня предъявления требования.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В течение 10 дней со дня предъявления соответствующего требования.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В течение 45 дней со дня предъявления соответствующего требования.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid windowtext; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В течение 10 дней со дня предъявления соответствующего требования.</p>
</td>
</tr>
</tbody>
</table>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Если вследствие продажи товара ненадлежащего качества Вы&nbsp;понесли убытки, Вы&nbsp;вправе потребовать полного их&nbsp;возмещения в течение 10 дней со дня предъявления соответствующего требования.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">При получении требования о возврате товара мы можем:</p>
<table border="1" cellspacing="0" cellpadding="10" style="background: rgb(242, 219, 219); margin: 0px; padding: 0px; border: 1pt solid windowtext; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">
<tbody style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td colspan="2" style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Провести проверку товара на наличие недостатков.</span></p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td colspan="2" style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Покупатель имеет право принять участие в проверке товара</p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td colspan="2" style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Провести экспертизу.</span></p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Экспертиза проводится за наш счёт</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если экспертиза установит, что недостатки связаны с обстоятельствами, за которые Продавец не отвечает, Покупатель возмещает:</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Стоимость экспертизы.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Стоимость транспортировки товара.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Стоимость хранения товара.</p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td colspan="2" style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Экспертиза проводится с учётом срока на возврат денежных средств</p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td colspan="2" style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если в результате проверки (экспертизы) будет выявлено, что за возникшие недостатки отвечаем мы, мы возвращаем деньги в течение 10 дней с момента получения требования от Покупателя.</p>
</td>
</tr>
</tbody>
</table>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Вы вправе оспорить заключение такой экспертизы в судебном порядке.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Если для замены товара ненадлежащего качества длительного пользования требуется более 7 дней, по Вашему требованию мы в течение 3 дней со дня предъявления требования о замене товара безвозмездно предоставим Вам во временное пользование на период ремонта или замены товар надлежащего качества, обладающий этими же основными потребительскими свойствами, обеспечив его доставку за свой счёт. Исключения составляют товары по&nbsp;<a href="http://www.consultant.ru/cons/cgi/online.cgi?req=doc&amp;base=LAW&amp;n=209736&amp;rnd=244973.123796971&amp;dst=100314&amp;fld=134#0" style="color: rgb(43, 43, 43); margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Перечню, утверждаемому Правительством РФ</a>, на которые это требование не распространяется.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В этот перечень входит в том числе:</span></p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Прогулочные суда и плавсредства.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Мебель.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Гражданское оружие, основные части гражданского и служебного огнестрельного оружия.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Срок возврата товара</span></p>
<table border="1" cellspacing="0" cellpadding="10" style="background: rgb(242, 219, 219); margin: 0px; padding: 0px; border: 1pt solid windowtext; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">
<tbody style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если установлен гарантийный срок или срок годности</span></p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если не установлен гарантийный срок</span></p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если Продавец оговорил&nbsp;недостатки при передаче товара</span></p>
</td>
</tr>
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В течение гарантийного срока или срока годности.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В разумный срок, но в пределах 2-х лет со дня передачи Вам товара, если более длительные сроки не установлены законом или договором. Вы должны доказать, что недостатки возникли до передачи товара или по причинам, возникшим до этого момента.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; background: rgb(218, 238, 243);"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">В этом случае возврат товара ненадлежащего качества невозможен.</p>
</td>
</tr>
</tbody>
</table>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Если предусмотренный договором гарантийный срок составляет менее 2 лет и недостатки товара обнаружены потребителем по истечении гарантийного срока, но в пределах 2 лет, мы также примем товар обратно или заменим его, если вы докажете, что недостатки товара возникли до его передачи потребителю или по причинам, возникшим до этого момента.</p>
<h3 style="font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; line-height: initial; color: rgb(36, 36, 36); margin: 20px 0px 22px; font-size: 1em; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; vertical-align: baseline; text-transform: uppercase; text-align: center; letter-spacing: 1.6px;">4.1. ОСОБЕННОСТИ ОБМЕНА И&nbsp;ВОЗВРАТА ТЕХНИЧЕСКИ СЛОЖНЫХ ТОВАРОВ НЕНАДЛЕЖАЩЕГО КАЧЕСТВА</h3>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">Товар может быть признан технически сложным согласно Перечню технически сложных товаров, утвержденному&nbsp;<a href="http://www.consultant.ru/cons/cgi/online.cgi?req=doc&amp;base=LAW&amp;n=204874&amp;fld=134&amp;dst=1000000001,0&amp;rnd=0.042517429408045704#0" style="color: rgb(43, 43, 43); outline: 0px; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Постановлением Правительства РФ от 10.11.2011 № 924 «Об утверждении перечня технически сложных товаров»</a>.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">К технически сложным товарам относятся в том числе:</span></p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Суда спортивные, туристские и прогулочные, катера, лодки, яхты и транспортные плавучие средства с двигателем внутреннего сгорания (с электродвигателем).</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Электрические водонагреватели с электрическим двигателем и (или) микропроцессорной автоматикой.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Электрифицированный инструмент (машины ручные и переносные электрические).</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Если Вы обнаружили недостатки в технически сложном или дорогостоящем товаре, мы:</span></p>
<table border="1" cellspacing="0" cellpadding="10" align="left" style="background: rgb(242, 219, 219); margin: 0px; padding: 0px; border: 1pt solid windowtext; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">
<tbody style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<tr style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Заменим на товар</span>&nbsp;этой же марки (модели, артикула) или на такой же товар другой марки (модели, артикула) с соответствующим перерасчётом покупной цены.</p>
</td>
<td style="padding: 10px; margin: 0px; border: 1pt solid black; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><p style="margin-bottom: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Примем товар обратно</span>&nbsp;и вернём уплаченную сумму.</p>
</td>
</tr>
</tbody>
</table>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">&nbsp;</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;"><span style="font-weight: 700; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Срок</span></p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">В течение 15 дней со дня передачи потребителю такого товара.</p>
<p style="margin-bottom: 0px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: inherit; font-family: &quot;Myriad Set Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; vertical-align: baseline; color: rgb(42, 42, 42); letter-spacing: 0.5px;">По истечении этого срока указанные требования подлежат удовлетворению в одном из следующих случаев:В товаре обнаружены существенные недостатки.</p>        </div>
            </div>
      </div>
</div>

<?php require(__DIR__ . "/files/html/footer.html");?>		
<script src="App/templates/files/js/link_for_version2.js"></script>
	
    </div>

</body></html>